#!/usr/bin/env bash
# Bring the MORPHIA hosted-MVP production stack up behind a reverse proxy.
#
#   ./scripts/prod-up.sh                  # generate .env + start
#   ./scripts/prod-up.sh --reset          # wipe volumes + reseed
#
# What this does:
#   1. Generates strong, unique secrets (SECRET_KEY, WORKER_AUTH_SECRET,
#      POSTGRES_PASSWORD, SEED_ADMIN_PASSWORD) and writes them to
#      infra/deployment/.env (gitignored).
#   2. Builds the production images from the production Dockerfiles.
#   3. `docker compose -f docker-compose.prod.yml up -d` starts the
#      internal services, the migration one-shot, and the Caddy edge.
#   4. Waits for /api/ready, seeds the demo workspace, and prints the
#      sign-in URL and credentials.

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

ENV_FILE="infra/deployment/.env"
COMPOSE="docker compose -f docker-compose.prod.yml"

if [[ "${1:-}" == "--reset" ]]; then
  echo "▸ stopping + wiping volumes"
  $COMPOSE down -v || true
  rm -f "$ENV_FILE"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "▸ generating strong secrets in $ENV_FILE"
  mkdir -p "$(dirname "$ENV_FILE")"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/prod-up.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')
WORKER_AUTH_SECRET=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')

POSTGRES_USER=morphia
POSTGRES_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
POSTGRES_DB=morphia

SEED_ADMIN_EMAIL=admin@morphia.example.com
SEED_ADMIN_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')

# Edit MORPHIA_DOMAIN to your real domain before going public, or use
# a Tailnet hostname like cypherdome.tail-net.ts.net.
FRONTEND_URL=http://localhost
ALLOWED_ORIGINS=http://localhost

ENVIRONMENT=production
DEBUG=false
EOF
  chmod 600 "$ENV_FILE"
fi

echo "▸ ensuring evidence volume is writable"
mkdir -p storage

echo "▸ building production images"
$COMPOSE build

echo "▸ starting the stack"
$COMPOSE up -d

echo "▸ waiting for the API"
for i in $(seq 1 60); do
  if curl -fsS http://localhost/api/ready 2>/dev/null | grep -q '"status":"ready"'; then
    break
  fi
  sleep 2
done

echo "▸ seeding the demo workspace"
$COMPOSE exec -T -e ENVIRONMENT=production api python -m app.seed || true

cat <<EOF

✓ MORPHIA hosted-MVP is up.

  Local URL:       http://localhost
  API health:      http://localhost/api/health
  System status:   http://localhost/settings (after sign-in)

  Admin email:     $(grep '^SEED_ADMIN_EMAIL' $ENV_FILE | cut -d= -f2-)
  Admin password:  $(grep '^SEED_ADMIN_PASSWORD' $ENV_FILE | cut -d= -f2-)
  Secrets file:    $ENV_FILE (chmod 600, gitignored)

  Next steps
   - Edit MORPHIA_DOMAIN in $ENV_FILE and restart `caddy` to put this
     behind a real domain + Let's Encrypt cert.
   - Or run \`cloudflared tunnel --url http://localhost\` for a free
     public hostname.
EOF
